# Copyright(C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

build_arguments:
- "PYTHON_VERSION=3.10"   # Cannot exceed Python 3.11 due to Aloha Gym / Mujoco 2.3.7 dependency
                          # https://pypi.org/project/mujoco/2.3.7/#files

environment_variables: #TODO: Update with your own HF token
- "HF_TOKEN=your_token_here" 
- "HSA_OVERRIDE_GFX_VERSION=11.0.0"

# Make sure calibration is persistent and models are available after ryzer exit
volume_mappings:
- "~/.cache/huggingface/lerobot/calibration/:/root/.cache/huggingface/lerobot/calibration"
- "$PWD/packages/robotics/lerobot/mounted:/ryzers/mounted"

# TODO: change to your robot and video device locations:
docker_extra_run_flags:
    - "--device=/dev/ttyACM_leader:/dev/ttyACM_leader"
    - "--device=/dev/ttyACM_follower:/dev/ttyACM_follower"
    - "--device=/dev/webcam_top:/dev/webcam_top"
    - "--device=/dev/webcam_front:/dev/webcam_front"
