# Copyright(C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

init_image: "rocm/pytorch:rocm6.3.3_ubuntu22.04_py3.10_pytorch_release_2.4.0"

environment_variables:
- "HSA_OVERRIDE_GFX_VERSION=11.0.0"
# Set your Hugging Face token here to access gated Llama2 models
# Get your token from: https://huggingface.co/settings/tokens
- "HF_TOKEN=<your_token_here>"

volume_mappings:
- "~/.cache/huggingface/:/root/.cache/huggingface/"
